In [17]:
import numpy as np
import pandas as pd

In [18]:
student_dict = {'Name': ['Joe', 'Nat', 'Harry'], 'Age': [20, 21, 19], 'Marks': [85.10, 77.80, 91.54]}

student_df = pd.DataFrame(student_dict)

student_df.head()

    Name  Age  Marks
0    Joe   20  85.10
1    Nat   21  77.80
2  Harry   19  91.54

In [19]:
student_df.describe()

        Age      Marks
count   3.0   3.000000
mean   20.0  84.813333
std     1.0   6.874484
min    19.0  77.800000
25%    19.5  81.450000
50%    20.0  85.100000
75%    20.5  88.320000
max    21.0  91.540000

In [20]:
list_Index = student_df.columns
print('Columns Names', list_Index)

Columns Names Index(['Name', 'Age', 'Marks'], dtype='str')

In [21]:
df_cars = pd.read_json('data/cars.json')

In [22]:
df_cars['Car']

0                  Chevrolet Vega
1             Chevrolet Vega (sw)
2             Chevrolet Vega 2300
3                 Chevrolet Woody
4      Chevrolete Chevelle Malibu
                  ...
156              Mercury Capri v6
157       Mercury Cougar Brougham
158         Mercury Grand Marquis
159                Mercury Lynx l
160               Mercury Marquis
Name: Car, Length: 161, dtype: str

In [23]:
df_cars[['Car', 'MPG', 'quantity']]

                            Car   MPG  quantity
0                Chevrolet Vega  25.0       177
1           Chevrolet Vega (sw)  22.0        91
2           Chevrolet Vega 2300  28.0        74
3               Chevrolet Woody  24.5       241
4    Chevrolete Chevelle Malibu  16.0       206
..                          ...   ...       ...
156            Mercury Capri v6  21.0       158
157     Mercury Cougar Brougham  15.0        27
158       Mercury Grand Marquis  16.5       332
159              Mercury Lynx l  36.0       425
160             Mercury Marquis  11.0       112

[161 rows x 3 columns]

In [24]:
df_cars[df_cars.columns[[0, 1, 2]]]

                            Car   MPG  Cylinders
0                Chevrolet Vega  25.0          4
1           Chevrolet Vega (sw)  22.0          4
2           Chevrolet Vega 2300  28.0          4
3               Chevrolet Woody  24.5          4
4    Chevrolete Chevelle Malibu  16.0          6
..                          ...   ...        ...
156            Mercury Capri v6  21.0          6
157     Mercury Cougar Brougham  15.0          8
158       Mercury Grand Marquis  16.5          8
159              Mercury Lynx l  36.0          4
160             Mercury Marquis  11.0          8

[161 rows x 3 columns]

### Frequency Analysis - Value Counts

In [25]:
# Sample DataFrame
data = {'Category': ['Electronics', 'Clothing', 'Electronics', 'Books', 'Books', 'Clothing']}

cat_df = pd.DataFrame(data)

cat_df.value_counts()

Category
Electronics    2
Clothing       2
Books          2
Name: count, dtype: int64

In [26]:
# Create the dataframe
sales_data={"Devices":['Laptop','iPhone','LED','LCD','Smart-Phone','Washing-Machine'],
            'Brand':['Lenovo','Apple','Samsung','Samsung','Samsung','Whirpool'],
            'Sales':[1000,2000,4000,2000,1000,4000],
            'Profit':[500,1000,1000,1500,1000,1500],
            'Pices left':[5000,4000,4000,5000,5000,1000]}

sales_df = pd.DataFrame(sales_data)

Frequency = sales_df['Brand'].value_counts()
print(Frequency)

frequent_product = Frequency[Frequency > 1].index[0]

print(Frequency)
print(f'This item appears more than once: {frequent_product}')

Brand
Samsung     3
Lenovo      1
Apple       1
Whirpool    1
Name: count, dtype: int64
Brand
Samsung     3
Lenovo      1
Apple       1
Whirpool    1
Name: count, dtype: int64
This item appears more than once: Samsung

In [27]:
data = {'Score': [85, 92, 88, 75, None, 90, None, 85]}

scores_df = pd.DataFrame(data)

In [28]:
score_counts = scores_df.value_counts(dropna=False)
print('Score:', score_counts)

Score: Score
85.0     2
NaN      2
92.0     1
88.0     1
75.0     1
90.0     1
Name: count, dtype: int64

### Rename a column in Pandas

In [29]:
tech = {
        'Courses': ["Python", ' DataAnalytics', 'MERN Stack', 'Data Engineering'],
        'Fee': [100, 2000, 250, 300],
        'Duration':['40days', '50days', '3 months', '1 year']
    }

tech_df = pd.DataFrame(tech)

In [30]:
tech_df = tech_df.rename(columns ={'Courses': 'Course Name'})

In [31]:
tech_df.head()

        Course Name   Fee  Duration
0            Python   100    40days
1     DataAnalytics  2000    50days
2        MERN Stack   250  3 months
3  Data Engineering   300    1 year